planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0

arm:
  planner_configs:
    - RRTConnectkConfigDefault
  projection_evaluator: joints(1_joint,2_joint)
  longest_valid_segment_fraction: 0.01
